name: Build and Test
on:
  push:
  pull_request:
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure git
        env:
           TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: "Install dependencies"
        run: sudo apt-get update && sudo apt-get install build-essential cmake qtbase5-dev qt5-qmake libprotobuf-dev protobuf-compiler libprotoc-dev protobuf-compiler-grpc libgrpc++-dev libgrpc-dev libqt5serialport5-dev google-mock libgmock-dev libgtest-dev libspdlog-dev libfmt-dev && sudo apt-get upgrade
      - name: "Install Google Test library"
        run: cd /usr/src/googletest/googletest/ && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib
      - name: "Install Google Mock library"
        run: cd /usr/src/googletest/googlemock/ && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib
      - name: "Update ldconfig"
        run: sudo ldconfig
      - name: "Install Armorial library"
        run: sudo sh install.sh
      - name: "Run tests"
        run: sudo sh run_tests.sh

